### PR TITLE
Add gemspec and Rakefile to ready to publish rubygems.org

### PR DESCRIPTION
**Pull request by cosmo0920**
Hi, @emsearcy !

It would be better to have gemspec in this project.
If this PR is acceptable, please publish into rubygems.org.

### CODE REVIEW

**Comment by mhulscher** [comment]
Any chance of this happening? Would be of great help.

**Comment by cosmo0920** [comment]
Any chance to merge this?
These patches help to install this plugin more easily.
Almost Fluentd users might want to its plugins via gem command.

**Comment by cosmo0920** [comment]
ping?

**Comment by cosmo0920** [comment]
@emsearcy If you have no time to maintain this plugin.
We can take over this project to keep maintaining.
See https://github.com/fluent-plugins-nursery/contact

We wish to know your response to this comment, thanks in advance.

**Comment by cosmo0920** [comment]
Thanks for merging this PR.
Could you publish this fluentd plugin into ruby gems.org with this Rakefile?

**Pull request merged**
